version: "3"

services:
  pg:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: 'example'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'develop'
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - 3081:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'example'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'
